// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.RobotFinal;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static CANTalon driveTrainCANTalonRearLeft;
    public static CANTalon driveTrainCANTalonFrontLeft;
    public static CANTalon driveTrainCANTalonRearRight;
    public static CANTalon driveTrainCANTalonFrontRight;
    public static RobotDrive driveTrainRobotDrive41;
    public static CANTalon clampCANTalonClamp;
    public static CANTalon elevatorCANTalonElev;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalonRearLeft = new CANTalon(1);
        
        
        driveTrainCANTalonFrontLeft = new CANTalon(2);
        
        
        driveTrainCANTalonRearRight = new CANTalon(3);
        
        
        driveTrainCANTalonFrontRight = new CANTalon(4);
        
    	driveTrainRobotDrive41 = new RobotDrive(driveTrainCANTalonRearLeft, driveTrainCANTalonFrontLeft,
                driveTrainCANTalonRearRight, driveTrainCANTalonFrontRight);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        clampCANTalonClamp = new CANTalon(6);
        
        
        elevatorCANTalonElev = new CANTalon(5);
    }
}
