// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.MecanumDriveTest;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon clampCANTalonClamp;
    public static CANTalon driveTrain2CANTalon1;
    public static CANTalon driveTrain2CANTalon2;
    public static CANTalon driveTrain2CANTalon3;
    public static CANTalon driveTrain2CANTalon4;
    public static RobotDrive driveTrain2RobotDrive2;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        clampCANTalonClamp = new CANTalon(6);
        
        driveTrain2CANTalon1 = new CANTalon(1);
        
        
        driveTrain2CANTalon2 = new CANTalon(4);
        
        
        driveTrain2CANTalon3 = new CANTalon(2);
        
        
        driveTrain2CANTalon4 = new CANTalon(3);
        
         
        driveTrain2RobotDrive2 = new RobotDrive(driveTrain2CANTalon1, driveTrain2CANTalon2,
              driveTrain2CANTalon3, driveTrain2CANTalon4);
        
        driveTrain2RobotDrive2.setSafetyEnabled(true);
        driveTrain2RobotDrive2.setExpiration(0.1);
        driveTrain2RobotDrive2.setSensitivity(0.5);
        driveTrain2RobotDrive2.setMaxOutput(1.0);
    }
}
