// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.RobotFinal.subsystems;

import org.usfirst.frc5571.RobotFinal.Robot;
import org.usfirst.frc5571.RobotFinal.RobotMap;
import org.usfirst.frc5571.RobotFinal.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Elevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	 CANTalon cANTalonElev = RobotMap.elevatorCANTalonElev;
    
    // Put methods for controlling this subsystem
    // here. Call these from CommandsS.
	 double axis;
		static double MAX_ELEV_CURRENT = 20.0;  // limit current to 3A  motor is rated at 36.91W 
		static double DOWN_SPEED = 400;  // position change per 10 ms
		static double UP_SPEED = -400;  // position change per 10 ms
		double p;
		double i;;
		double d;
		double f;
		int izone;
		double ramprate;  // this should leave the ramp rate uncapped.
		int profile;
		boolean servoHereFlag;
		double servoAtThisPosition;



		public void initCanPID() {

			// Set PID values for Velocity and Position Mode here in profile 0
			p = .6;
			i = .00015;
			d = 0.06;
			f = 0.0005;
			izone = 0;
			ramprate = 36;  // this should leave the ramp rate uncapped.
			profile = 0;
			cANTalonElev.setPID(p, i, d, f, izone, ramprate, profile);

			// Set PID values for Servo In Place Posisiotn Mode here in profile 1
			p = .6;
			i = .00015;
			d = 0.06;
			f = 0.0005;
			izone = 0;
			ramprate = 36;  // this should leave the ramp rate uncapped.
			profile = 1;
			cANTalonElev.setPID(p, i, d, f, izone, ramprate, profile);

			// Specify Quadrature Encoder
			cANTalonElev.setFeedbackDevice(CANTalon.FeedbackDevice.QuadEncoder);
			cANTalonElev.reverseSensor(false);
			//Reverse = true for gripper motor
			//Reverse = false for pulley

		}
		
		public void limitSwitchInit() {
			cANTalonElev.enableBrakeMode(true);
			cANTalonElev.enableLimitSwitch(true, true);
		}

		// Change to closed loop control mode and hold the current position
		public void positionMode() {
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Position);
			cANTalonElev.set(cANTalonElev.getPosition());
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");
		}

		// Change to closed loop control mode and move "count" ticks 
		public void positionMoveByCount(double count) {
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Position);
			cANTalonElev.set((cANTalonElev.getPosition()+count));
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");

		}

		// Change to Closed Loop Velocity Mode and
		public void speedMode() {
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Speed);
			axis = Robot.oi.xboxController.getY();
			cANTalonElev.set(axis*12.0); // need to scale the voltage by the joystick values;
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");

		}

		public void downElev() {
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Speed);
			cANTalonElev.set(DOWN_SPEED);
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");

		}

		public void upElev() {
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Speed);
			cANTalonElev.set(UP_SPEED);
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");

		}


		public void servoHere(){
			if (!servoHereFlag){ // first time through, so set flag and get the current position
				servoHereFlag = true;
				servoAtThisPosition = cANTalonElev.getPosition()+16;
				cANTalonElev.setProfile(1);

			}
			if (!elevCurrenLimited()){
				cANTalonElev.changeControlMode(CANTalon.ControlMode.Position);
				cANTalonElev.set(servoAtThisPosition);
				SmartDashboard.putString("Elev Servo Status", "ServoActive");
			}
			else{
				cANTalonElev.changeControlMode(CANTalon.ControlMode.PercentVbus);
				//cANTalonElev.set(0);
				SmartDashboard.putString("Elev Servo Status", "CurrentLimited");
			}
		}


		public void holdCurrentPosition(){
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.Position);
			cANTalonElev.set(cANTalonElev.getPosition());
		}

		public void disable_ElevMotor(){
			servoHereFlag = false;
			cANTalonElev.setProfile(0);
			cANTalonElev.changeControlMode(CANTalon.ControlMode.PercentVbus);
			cANTalonElev.set(0);
			SmartDashboard.putString("Elev Servo Status", "Servo Inactive");

		}

		public Boolean elevCurrenLimited(){ 
			return(cANTalonElev.getOutputCurrent() > MAX_ELEV_CURRENT);
		}


    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void showCanTalonStatus() {

    	double currentAmps = cANTalonElev.getOutputCurrent();
    	double outputV = cANTalonElev.getOutputVoltage();
    	double busV = cANTalonElev.getBusVoltage();
    	double quadEncoderPos = cANTalonElev.getEncPosition();
    	double quadEncoderVelocity = cANTalonElev.getEncVelocity();
    	double selectedSensorPos = cANTalonElev.getPosition();
    	double selectedSensorSpeed = cANTalonElev.getSpeed();
    	double Iaccum = cANTalonElev.GetIaccum();
    	double encoderErr = cANTalonElev.getClosedLoopError();

    		SmartDashboard.putNumber("Elev Current", currentAmps);
    		SmartDashboard.putNumber("Elev Output Voltage", outputV);
    		SmartDashboard.putNumber("Elev Bus Voltage", busV);
    		SmartDashboard.putNumber("Elev Encoder Position", quadEncoderPos);
    		SmartDashboard.putNumber("Elev Encoder Velocity", quadEncoderVelocity);
    		SmartDashboard.putNumber("Elev Position", selectedSensorPos);
    		SmartDashboard.putNumber("Elev Speed", selectedSensorSpeed);
    		SmartDashboard.putNumber("ELev I Accumulation", Iaccum);
    		SmartDashboard.putNumber("Elev Closed Loop Err", encoderErr);
    		SmartDashboard.putBoolean("Elev ServoHere Flag", servoHereFlag);


    }

}


